function names = featureNames()
%FEATURENAMES Feature names mapped from ExtractFeati_OPT output.

    names = {'hit','hittime','channel','Amp_dB','Dur_us','Energy_V2', ...
        'ZCR_pct','RiseTime_us','TempCentroid_us','alpha', ...
        'PP2_1','PP2_2','PP2_3','PP2_4', ...
        'FC2_kHz','PF2_kHz','SSpread_kHz','SSkew','SKurt','SSlope', ...
        'SRoff_kHz','SsqrtSpreadP_kHz','SSkewP','SKurtP','SRon_kHz', ...
        'WPE1','WPE2','WPE3','WPE4','WPE5','WPE6','WPE7','WPE8', ...
        'Entropy'};
end
