function ui = buildMainUI(cfg)
%BUILDMAINUI Create the main UI with responsive pixel-based layout.

    L = hexvis.ui.layoutMainUI();

    ui.fig = figure('Name', cfg.app.name, 'NumberTitle', 'off', ...
        'Color', [1 1 1], 'Position', L.fig, 'MenuBar', 'figure', ...
        'Toolbar', 'figure', 'HandleVisibility', 'callback', ...
        'Resize', 'on');

    ui.panCtrl = uipanel('Parent', ui.fig, 'Title', 'Controls', 'FontWeight', 'bold', ...
        'Units', 'pixels', 'BackgroundColor', [1 1 1]);
    ui.panTable = uipanel('Parent', ui.fig, 'Title', 'Events', 'FontWeight', 'bold', ...
        'Units', 'pixels', 'BackgroundColor', [1 1 1]);
    ui.panPlot = uipanel('Parent', ui.fig, 'Title', 'Preview', 'FontWeight', 'bold', ...
        'Units', 'pixels', 'BackgroundColor', [1 1 1]);

    ui.secFile = uipanel('Parent', ui.panCtrl, 'Title', 'File', ...
        'Units', 'pixels', 'BackgroundColor', [1 1 1]);
    ui.secRun = uipanel('Parent', ui.panCtrl, 'Title', 'Run', ...
        'Units', 'pixels', 'BackgroundColor', [1 1 1]);
    ui.secVis = uipanel('Parent', ui.panCtrl, 'Title', 'Visualization', ...
        'Units', 'pixels', 'BackgroundColor', [1 1 1]);
    ui.secStatus = uipanel('Parent', ui.panCtrl, 'Title', 'Status', ...
        'Units', 'pixels', 'BackgroundColor', [1 1 1]);

    fs = 9;
    fsSmall = 8;

    % ------- File -------
    ui.btnLoad = uicontrol(ui.secFile, 'Style', 'pushbutton', 'String', 'Load .wave', ...
        'FontSize', fs, 'Units', 'pixels');
    ui.txtFile = uicontrol(ui.secFile, 'Style', 'edit', 'String', '(none)', ...
        'FontSize', fs, 'Enable', 'inactive', 'Max', 2, 'HorizontalAlignment', 'left', ...
        'Units', 'pixels', 'BackgroundColor', [1 1 1]);
    ui.txtFileInfo = uicontrol(ui.secFile, 'Style', 'text', 'FontSize', fsSmall, ...
        'String', 'No file loaded', 'BackgroundColor', [1 1 1], ...
        'Units', 'pixels', 'HorizontalAlignment', 'left');

    % ------- Run -------
    ui.btnAIC = uicontrol(ui.secRun, 'Style', 'pushbutton', 'String', 'Run AIC', ...
        'FontSize', fs, 'Units', 'pixels');
    ui.btnFeat = uicontrol(ui.secRun, 'Style', 'pushbutton', 'String', 'Run Features', ...
        'FontSize', fs, 'Units', 'pixels');
    ui.btnSettings = uicontrol(ui.secRun, 'Style', 'pushbutton', 'String', 'Settings...', ...
        'FontSize', fs, 'Units', 'pixels');
    ui.txtChannel = uicontrol(ui.secRun, 'Style', 'text', 'FontSize', fsSmall, ...
        'String', sprintf('S1 = ch %d    S2 = ch %d', cfg.channels.S1, cfg.channels.S2), ...
        'BackgroundColor', [1 1 1], 'Units', 'pixels', 'HorizontalAlignment', 'left');
    ui.txtGeom = uicontrol(ui.secRun, 'Style', 'text', 'FontSize', fsSmall, ...
        'String', sprintf('L = %.1f mm    v = %.1f m/s', cfg.geom.L_mm, cfg.geom.v_ms), ...
        'BackgroundColor', [1 1 1], 'Units', 'pixels', 'HorizontalAlignment', 'left');

    % ------- Visualization -------
    ui.lblTFMode = uicontrol(ui.secVis, 'Style', 'text', 'String', 'TF mode:', 'FontSize', fs, ...
        'BackgroundColor', [1 1 1], 'HorizontalAlignment', 'left', 'Units', 'pixels');
    ui.popTF = uicontrol(ui.secVis, 'Style', 'popupmenu', 'FontSize', fs, ...
        'String', {'CWT','tfrsp'}, 'Value', 1, 'Units', 'pixels', 'BackgroundColor', [1 1 1]);
    ui.lblFmax = uicontrol(ui.secVis, 'Style', 'text', 'String', 'Fmax (kHz):', 'FontSize', fs, ...
        'BackgroundColor', [1 1 1], 'HorizontalAlignment', 'left', 'Units', 'pixels');
    ui.edFmax = uicontrol(ui.secVis, 'Style', 'edit', 'FontSize', fs, ...
        'String', num2str(cfg.vis.fmax_kHz), 'BackgroundColor', [1 1 1], 'Units', 'pixels');
    ui.chkSharedCB = uicontrol(ui.secVis, 'Style', 'checkbox', 'FontSize', fsSmall, ...
        'String', 'shared colorbar', 'Value', double(cfg.vis.sharedColorbar), ...
        'BackgroundColor', [1 1 1], 'Units', 'pixels', 'HorizontalAlignment', 'left');
    ui.lblStart = uicontrol(ui.secVis, 'Style', 'text', 'String', 'Start (us):', 'FontSize', fs, ...
        'BackgroundColor', [1 1 1], 'HorizontalAlignment', 'left', 'Units', 'pixels');
    ui.edStartUs = uicontrol(ui.secVis, 'Style', 'edit', 'FontSize', fs, ...
        'String', num2str(cfg.vis.window.start_us), 'BackgroundColor', [1 1 1], 'Units', 'pixels');
    ui.lblLength = uicontrol(ui.secVis, 'Style', 'text', 'String', 'End (us):', 'FontSize', fs, ...
        'BackgroundColor', [1 1 1], 'HorizontalAlignment', 'left', 'Units', 'pixels');
    ui.edWinUs = uicontrol(ui.secVis, 'Style', 'edit', 'FontSize', fs, ...
        'String', num2str(localDefaultEndUs(cfg.vis.window)), 'BackgroundColor', [1 1 1], 'Units', 'pixels');

    % ------- Status -------
    ui.txtStatus = uicontrol(ui.secStatus, 'Style', 'edit', 'Enable', 'inactive', ...
        'FontSize', fs, 'Max', 10, 'Min', 0, 'HorizontalAlignment', 'left', ...
        'String', 'Ready.', 'BackgroundColor', [1 1 1], 'Units', 'pixels');

    % ------- Table -------
    ui.tbl = uitable(ui.panTable, 'Data', cell(0,1), 'ColumnName', {'eventID'}, ...
        'Units', 'pixels', 'ColumnEditable', false, 'FontSize', fs, 'ColumnWidth', 'auto');
    ui.btnPrev = uicontrol(ui.panTable, 'Style', 'pushbutton', 'String', 'Prev', ...
        'FontSize', fs, 'Units', 'pixels');
    ui.btnNext = uicontrol(ui.panTable, 'Style', 'pushbutton', 'String', 'Next', ...
        'FontSize', fs, 'Units', 'pixels');
    ui.txtSelected = uicontrol(ui.panTable, 'Style', 'text', 'FontSize', fs, ...
        'String', 'Selected: 0 / 0', 'BackgroundColor', [1 1 1], ...
        'Units', 'pixels', 'HorizontalAlignment', 'right');

    % ------- Axes -------
    ui.axS1t = axes('Parent', ui.panPlot, 'Units', 'pixels', 'FontSize', fs);
    ui.axS2t = axes('Parent', ui.panPlot, 'Units', 'pixels', 'FontSize', fs);
    ui.axS1f = axes('Parent', ui.panPlot, 'Units', 'pixels', 'FontSize', fs);
    ui.axS2f = axes('Parent', ui.panPlot, 'Units', 'pixels', 'FontSize', fs);
    ui.axS1tf = axes('Parent', ui.panPlot, 'Units', 'pixels', 'FontSize', fs);
    ui.axS2tf = axes('Parent', ui.panPlot, 'Units', 'pixels', 'FontSize', fs);
    ui.cbTF = [];

    axList = {ui.axS1t, ui.axS2t, ui.axS1f, ui.axS2f, ui.axS1tf, ui.axS2tf};
    for i = 1:numel(axList)
        grid(axList{i}, 'on');
        box(axList{i}, 'on');
    end
    setappdata(ui.fig, 'hexvis_ui_handles', ui);
    set(ui.fig, 'ResizeFcn', @(src,~) hexvis.ui.applyMainResponsiveLayout(src));
    hexvis.ui.applyMainResponsiveLayout(ui.fig);
end

function end_us = localDefaultEndUs(W)
    if isfield(W, 'end_us') && isfinite(W.end_us)
        end_us = W.end_us;
    elseif isfield(W, 'length_us') && isfinite(W.length_us)
        start_us = 0;
        if isfield(W, 'start_us') && isfinite(W.start_us), start_us = W.start_us; end
        end_us = start_us + W.length_us;
    else
        end_us = 500;
    end
end
